# 使用 Python 官方镜像
FROM python:3.9

# 工作目录设置为 /app
WORKDIR /app

# 复制 requirements.txt 到容器的 /app
COPY ./requirements.txt /app/requirements.txt

# 安装依赖
RUN pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt

# 复制后端代码到容器的 /app
COPY . /app

# 暴露端口
EXPOSE 8000

# 运行 Django 服务
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
